<a href="https://colab.research.google.com/github/joshuajhchoi/ai2learn/blob/master/%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EC%B2%98%EC%9D%8C%ED%95%98%EB%8A%94_%EB%B6%84%EB%93%A4%EC%9D%84_%EC%9C%84%ED%95%9C_8%EC%8B%9C%EA%B0%84_%EB%A7%8C%EC%97%90_%EC%9D%B4%ED%95%B4%ED%95%98%EB%8A%94_%EB%A8%B8%EC%8B%A0_%EB%9F%AC%EB%8B%9D_%EA%B8%B0%EC%B4%88_%EC%88%98%EC%97%85_(3)_NumPy_%EA%B8%B0%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

목차

1. 파이썬 기초 문법 이해하기 (2시간 15분)
2. 주피터노트북 및 Colab 이해 (15분)

###3. NumPy 기본 (30분)
4. Matplotlib 기본 이해 (30분)
5. Seaborn 기본 이해 (30분)
6. 통계 필요사항 기본 이해 (30분)
7. Pandas 기본 이해 (30분)
8. ScikitLearn 기본 이해 (30분)
9. 머신러닝 알고리즘 개요 이해 (30분)
10. Kaggle Titanic 입문하기 (2시간)

####6시간 버전
1. 파이썬 기초 문법 이해하기 (1시간 30분)   
2. NumPy 기본 (30분)
3. Matplotlib 기본 이해 (30분)
4. Seaborn 기본 이해 (30분)
5. Pandas 기본 이해 (30분)
6. ScikitLearn 기본 이해 (30분)
7. Kaggle Titanic 입문하기 (2시간)

##NUMPY
Numpy는 Python의 과학 컴퓨팅을 위한 핵심 라이브러리입니다. 고성능 다차원 배열 객체와 이러한 배열 작업을위한 도구를 제공합니다. 

####Arrays (배열)
* 우린 수학에서 행렬을 배웠을 것입니다.
* 여기서는 수학의 행렬과 다르게 배열(array)을 1차원 이상의 변수를 말한다 
*  1차원 리스트를 다차원으로 빠르게 쓴다고 생각하면 됩니다.
* 우리가 리스트를 쓸 때 바이너리 코드로 상당히 긴 것을 사용하는데 Numpy는 적게 써서 자원을 아껴 준다고 생각하면 됩니다. 
* 또한 메모리의 배열 적인 면에서도 더 빠르게 할 수 있는 요소를 가지고 있는데 이 것은 여기서 이야기 하지 않도록 합니다.
* 일단 예를 보면서 이해해 봅니다.

####import
*우선 numpy를 import 합니다.

In [0]:
import numpy as np

#TASK 1– Creating 1D Array


##학습 내용
* NumPy를 배우는 것은 Array를 배우는 것과 거의 같다고 생각하면 됩니다.
* 우선 import를 하고, 1차원 array를 만들어 봅니다. 


##문법

        import numpy as np
        var = np.array([item1, item2.....])



## 연습

        import numpy as np
        var = np.array([item1, item2.....])
        print (var)

* 에디터에 넣고 출력해 봅니다.


##주의
* array는 수학의 행렬과 비슷하나 살짝 다른 점이 있다는 것을 염두에 두세요. 나중에 배웁니다.



##코딩 부분

In [0]:
import numpy as np
var = np.array([1,2,3])
print (var)

[1 2 3]


#TASK 2– Creating 2D Array


##학습 내용
* *2차원 array를 연습해 보겠습니다.
* 1차원이 

        1	2	3

이었다면

2차원이란

    	1	2	3
    	4	5	6

같은 모양을 말합니다

* 위의 경우 2 X 3 행렬인 것입니다. 

##문법

        import numpy as np
        var = np.array([[item11, item12.....], [item21, item22....]])



## 연습

        import numpy as np
        var = np.array([[item11, item12.....], [item21, item22....]])
        print (var)

* 에디터에 넣고 출력해 봅니다.


##주의
* [ [] ] 두 겹임을 기억하세요



##코딩 부분

In [0]:
import numpy as np
var = np.array([[1,2,3], [4,5,6]])
print (var)

[[1 2 3]
 [4 5 6]]


#TASK 3– Creating 3D+ Array


##학습 내용
* 3차원 array를 연습해 보겠습니다.
* 이는 2차원을 겹으로 만드는 것으로 만듭니다.

##문법

        import numpy as np
        var = np.array([[item111, item112.....], [item121, item122....]], [item211, item112.....], [item221, item122....]]])



## 연습

        import numpy as np
        var = np.array([[item111, item112.....], [item121, item122....]], [item211, item112.....], [item221, item122....]]])
        print (var)

* 에디터에 넣고 출력해 봅니다.


##주의
* [ [[]] ] 세 겹임을 기억하세요



##코딩 부분

In [0]:
import numpy as np
var = np.array([[[1,2,3], [4,5,6]], [[1,2,3],[4,5,6]]])
print (var)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


#TASK 4 - Checkig Datatype


##학습 내용
* dtype은 어떤 종류의 데이터인지 (integer인지 float인지 등)을 알려 줍니다.
* 일반적으로 float이 더 많은 메모리를 잡아 먹고, integer도 가능하면 메모리를 덜 쓰도록 해야지 결과가 빠르게 나오기 때문에 이는 중요합니다.



##문법

	variable.dtype
	



## 연습

	import numpy as np
	var = np.array([int1, int2.....])
	print (var.dtype)
	
 
	import numpy as np
	var = np.array([float1, float2.....] ) 
	print (var.dtype)



* 에디터에 넣고 출력해 봅니다.


* 개별 int32인지 int16인지 등의 사이즈 지정도 가능


##코딩 부분


In [0]:
import numpy as np
var = np.array([1,2,3])
print (var.dtype)


import numpy as np
var = np.array([1.0,2.0,3.0])
print (var.dtype)

int64
float64


#TASK 5 Checkig Dimensions


##학습 내용
* 자신의 array가 몇 차원인지 확인해 봅니다.


##문법

        variable.ndim




## 연습

        import numpy as np
        var = np.array([[item111, item112.....], [item121, item122....]], [item211, item112.....], [item221, item122....]]])
    	print (var.ndim) 	# n-dimension 확인/ 주피터 노트북 등을 쓰면 굳이 프린트 하지 않아도 되나 여기서는 프린트해서 확인


* 에디터에 넣고 출력해 봅니다.


##주의
* 


##코딩 부분

In [0]:
import numpy as np
var = np.array([[[1,2,3], [4,5,6]], [[1,2,3],[4,5,6]]])
print (var.ndim)


var = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print (var.ndim)

3
3


#TASK 6 - Checkig Shape

##학습 내용
* Shape은 자신의 행렬이 몇 X 몇 행렬인지를 보여 줍니다.


##문법

	        variable.shape



## 연습

        import numpy as np
        var = np.array([[item111, item112.....], [item121, item122....]], [item211, item112.....], [item221, item122....]]])
        print (var.shape)

* 에디터에 넣고 출력해 봅니다.


##주의
* 


##코딩 부분

In [0]:
import numpy as np
var = np.array([[[1,2,3], [4,5,6]], [[1,2,3],[4,5,6]]])
print (var.shape)


var = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print (var.shape)

var = np.array([[1,2,3], [4,5,6]])
print (var.shape)

(2, 2, 3)
(1, 3, 3)
(2, 3)


#TASK 7 - Checkig Size


##학습 내용
* Size 는 얼마나 많은 메모리를 NumPy가 차지 하는지를 알려 줍니다.
* 주피터 노트북에서는 약간 다르게 할 수 있음 



##문법


        variable.size




## 연습

        import numpy as np
        var = np.array([[item111, item112.....], [item121, item122....]], [item211, item112.....], [item221, item122....]]])
        print (var.size)

* 에디터에 넣고 출력해 봅니다.


##주의
* 주니퍼 노트북에서는 개별 item size도 확인 가능


##코딩 부분

In [0]:
import numpy as np
var = np.array([[[1,2,3], [4,5,6]], [[1,2,3],[4,5,6]]])
print (var.size)

12


#Task 8 - Indexing - 1D Array


##학습 내용
* 1차원 Array에서 아이템을 인덱싱 합니다.
* 리스트와 별 다름이 없습니다.
* 아시다시피 위치는 0,1,2,3,4,.....순서로 갑니다 

##문법

	variable[위치]
	



## 연습

	import numpy as np
	var = np.array([1,2,3,4,5])
	print (var[2])
	

##주의
* var[2]이므로 3번째 아이템이 출력이 되어야 합니다.



##코딩 부분

In [0]:
import numpy as np
var = np.array([1,2,3,4,5])
print (var[2])

3


#Task 9 - Indexing - 2D Array


##학습 내용
* 2차원 Array에서 아이템을 인덱싱 합니다.
* 행과 열의 위치를 인덱싱합니다. 예를 들어 2행의 3열이면 [1,2]로 인덱싱합니다.

##문법

	variable[행위치, 열위치]
	

## 연습

	import numpy as np
	var = np.array([[1,2,3,4,5], [6,7,8,9,10]])
	print (var[1,2])
	

##주의
* var[1,2]이므로 2행 3번째 아이템 8이 출력이 되어야 합니다.



##코딩 부분

In [0]:
import numpy as np
var = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print (var[1,2])

8


#Task 10 - Indexing - 3D Array


##학습 내용
* 3차원 Array에서 아이템을 인덱싱 합니다.
* 행과 열의 위치를 인덱싱합니다. 예를 들어 2번째 2행의 3열이면 [0,1,2]로 인덱싱합니다.

##문법

	variable[행위치, 열위치]
	

## 연습

	import numpy as np
	var = np.array([[[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]]])
	print (var[0,2,3])
	

##주의
* var[0,2,3]이므로 3행 4번째 아이템 14가 출력이 되어야 합니다.
* 주피터 노트북에서는 약간 다르게 할 수 있음 (slicing)


##코딩 부분


In [0]:
import numpy as np

var = np.array([[[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]]])
print (var[0,2,3])

14


#### 1X3

    POSITION        0   1   2   3   4
    ITEM            1   2   3   4   5

#### 2X3

    POSITION        0,0 0,1 0,2 0,3 0,4
    ITEM            1   2   3   4   5
    POSITION        1,0 1,1 1,2 1,3 1,4
    ITEM            6   7   8   9   10
    
#### 3X3

    POSITION        0,0,0   0,0,1  0,0,2   0,0,3    0,0,4
    ITEM            1       2       3       4       5
    POSITION        0,1,0   0,1,1  0,1,2   0,1,3    0,1,4
    ITEM            6       7       8       9       10
    POSITION        0,2,0   0,2,1  0,2,2   0,2,3    0,2,4
    ITEM            11      12      13      14      15

#Task 11 - Replacing Items


##학습 내용
* Array에서 특정 아이템을 변경합니다.


##문법

	variable[본래위치] = 바꿀내용
	

## 연습

	var = np.array([[1,2,3,4,5], [6,7,8,9,10]])
	var[1,1] = 100

##주의
* 



##코딩 부분

In [0]:
import numpy as np
var = np.array([[1,2,3,4,5], [6,7,8,9,10]])
var[1,1] = 100
print (var)

[[  1   2   3   4   5]
 [  6 100   8   9  10]]


#Task 12 - Creating Arrays with zeroes, ones and others


##학습 내용
* 모두 0으로된 1로된 또는 다른 숫자로 된 Array를 만들어 본다.


##문법

	np.zeros(shape)
	np.ones(shape)
	np.full( (shape), 통일된 아이템)

## 연습

	# 0 3개로 된 1차원
	 np.zeros(3)
	# 1 2X3개로 된 2차원
	 np.oness([2,3])
	# 5 3X3 개로 된 3차원
	 np.full([3,3], 5)

##주의
* 



##코딩 부분

In [0]:
import numpy as np
print (np.zeros(3))
print (np.zeros([2,3]))
print (np.zeros([3,3]))

print (np.ones(3))
print (np.ones([2,3]))
print (np.ones([3,3]))

print (np.full(3, 5))
print (np.full([2,3], 5))
print (np.full([3,3], 5))


[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[5 5 5]
[[5 5 5]
 [5 5 5]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]


#Task 13 - Creating Arrays with Random Numbers


##학습 내용
* 랜덤 인테저나 플롯으로 된 array를 생성해 본다.


##문법

	np.random.rand(shape)	        #float
	np.random.randint(shape)	     #integer

## 연습

	# 3X3 random float
	 np.random.rand(3,3)
	# 3X3 random integer
	 np.random.randint(최소숫자, 최대숫자-1, size =(3,3))

##주의
* 이 부분은 아래 에디터로는 되지 않아서 주피터 노트북에서 다음과 같이 한다

##코딩 부분

In [0]:
np.random.rand(3,3)

array([[0.53585728, 0.21958508, 0.47751226],
       [0.64869176, 0.68105183, 0.89906729],
       [0.23894475, 0.74705175, 0.60315731]])

* Random Integer Arrays

In [0]:
np.random.randint(1,9 size=(3,3))

SyntaxError: ignored

#Task 14 - Methods for Creating Arrays


##학습 내용
* Identity Matrix 를 배웁니다.
* 반복하는 Matrix를 만들어 봅니다.

##문법

	np.identity(행렬사이즈) # 예를 들어 3이다 하면 3X3 행렬에 대각선으로 1,1,1 이 있는 매트릭스를 만듭니다.

## 연습

	np.identity(3)
	np.repeat(var, 차원)
	
##주의
* 아이덴티티 매트릭스는 행과 열의 숫자가 항상 같습니다. 2X2, 3X3, 4X4
* repeat은 주피터노트북에서 연습해 보겠습니다.

##코딩 부분

In [0]:
import numpy as np
print (np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [0]:
var = np.array([[1,2,3]])
rep = np.repeat(var,3, axis=0)
print (rep)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


#Task 14 - Methods for Creating Arrays


##학습 내용
* np.copy() 메소드를 배웁니다.
* np.eye() 메소드를 배웁니다  (identity matrix와 같음) 
* np.empty() 메소드를 배웁니다.
* np.like() 메소드를 배웁니다.
* np.linspace() 메소들르 배웁니다.


##문법

	var.copy()
	np.eye(행렬수)
	np.empty(행,렬)
	
	np.zeros_like	# 기존 array의 차원을 본 뜬 0 행렬을 만듭니다.
	np.ones_like	# 기존 array의 차원을 본 뜬 1 행렬을 만듭니다.
	
	np.linspace(시작, 끝, 나누기갯수)	#시작부터 끝까지 사이를 나누기 갯수만큼 균등하게 나누어 줍니다.		


## 연습

	a = np.array([1,2,3])
	b = a.copy()
	print (b)

##주의
* 일부는 주피터노트북에서 연습해 보겠습니다.

##코딩 부분

In [0]:
import numpy as np


a = np.array([[1,2,3],[1,2,30]])
b = a.copy()
print (b)

print (np.empty(3,3))

print (np.linspace(0,10,4))


[[ 1  2  3]
 [ 1  2 30]]


TypeError: ignored

####내용

* np.eye() 메소드를 배웁니다  (identity matrix와 같음) 
* np.zeros_like	# 기존 array의 차원을 본 뜬 0 행렬을 만듭니다.
* np.ones_like	# 기존 array의 차원을 본 뜬 1 행렬을 만듭니다.
* np.arrange(시작점, 끝점, 단계)	# 예를 들어 0, 5, 1이라면 0부터 4까지 1씩 올라가면서 array 생성

In [0]:
a = np.eye(3)
print (a)
        
print (np.zeros_like(a))
print (np.ones_like(a))
print (np.arrange(0, 10, 2))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


AttributeError: ignored